[project]
name = "lightsurf"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "R. Garcia-Dias", email = "rafaelagd@gmail.com" },
]
requires-python = ">=3.12"
dependencies = [
    "astropy>=6.1.4",
    "pandas>=2.2.3",
    "tqdm>=4.66.5",
    "matplotlib>=3.9.2",
    "click>=8.1.7",
    "pandera>=0.20.4",
    "xgboost>=2.1.1",
    "pydantic>=2.9.2",
    "scikit-learn>=1.5.2",
    "seaborn>=0.13.2",
    "mlflow>=2.17.0",
    "torch>=2.5",
    "pyyaml>=6.0.2",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "frictionless>=5.18.1",
    "ipykernel>=6.29.5",
    "isort>=6.0.1",
    "mypy>=1.16.1",
    "pyqt5>=5.15.11",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.1",
    "taskipy>=1.14.1",
]

[project.scripts]
lightsurf = "lightsurf:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.coverage.report]
exclude_lines = ["if __name__ == .__main__.:"]
omit = ["*/src/lightsurf/exploratory_analysis/*"]

[tool.pytest.ini_options]
python_files = ["test_*.py", "*_test.py"]
addopts = ["--cov=lightsurf", "--cov-report=term-missing"]
filterwarnings = ["ignore::DeprecationWarning"]

[tool.ruff]
exclude = [
    "*/migrations/*",
    "*/settings.py",
    "*/wsgi.py",
    "*/asgi.py",
    "*/mlflwo/*",
    "*/__pycache__/*",
]

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PT']


[tool.mypy]
ignore_missing_imports = true
exclude = ["src/lightsurf/domain/services/data/combine_fits.py"]


[tool.taskipy.tasks]
test = "pytest"
lint = "mypy ."
format = "ruff check . --fix"
pre_test = "task format && task lint"
post_test = "coverage html"
train = "uv run python src/lightsurf/train.py"
mlflow = "uv run mlflow server --host 0.0.0.0 --port 5000"
download_allstar = "uv run src/lightsurf/domain/services/data/download_all_star_list.py --file_url https://data.sdss.org/sas/dr17/apogee/spectro/aspcap/dr17/synspec_rev1/allStar-dr17-synspec_rev1.fits --destination data/allStar-dr17-synspec_rev1.fits"
filter_m_dwarfs = "uv run src/lightsurf/domain/services/data/filter_m_dwarfs.py"
download_spectra = "uv run src/lightsurf/domain/services/data/download_spectra.py"
download = "task download_allstar && task filter_m_dwarfs && task download_spectra"
combine_spectra = "uv run src/lightsurf/domain/services/data/combine_fits.py"

